force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>Project-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/project_code__c.field-meta.xml
<CustomField>
    <fullName>project_code__c</fullName>
    <label>project code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TimeSheetController.cls
public with sharing class TimeSheetController {

    public class OptionWrapper {
        @AuraEnabled public String label;
        @AuraEnabled public String value;

        public OptionWrapper(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
    
    public class TimeSheetWrapper{
        @AuraEnabled
        public List<OptionWrapper> projectOptions{get; set;}
    }

    @AuraEnabled
    public static TimeSheetWrapper getInitData() {
        TimeSheetWrapper rec = new TimeSheetWrapper();
        List<OptionWrapper> projectOptions = new List<OptionWrapper>();
        List<Project__c> projectRecords = getProjectsDetail();
        for(Project__c projectRecord: projectRecords) {
            projectOptions.add(new OptionWrapper(projectRecord.project_code__c, projectRecord.Id));
        }
        rec.projectOptions = projectOptions;
        return rec;
    }

    @AuraEnabled
   public static List<Project__c> getProjectsDetail() {
        return [select id, Name, project_code__c from Project__c];
   }
}